function plot_fpr(false_positive_rate, bootstrap_output, figure_size, reference_fpr, sample_size_ticks, figure_font_size, xaxis_type, colormap_correlations, colormap_average, dataset_filename, save_figures, output_folder)
% coded by Luca Cecchetti & Giacomo Handjaras, IMT-Lucca, Italy
% vers 20220619

%figure_title = strrep(strrep(dataset_filename,'.csv',''),'_',' ');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% UNCORRECTED %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
figure('Position', figure_size, 'Name','Uncorrected');
axes('Position',[.25 .25 .45 .45])
%subplot(1,3,1)
hold on
U = plot(bootstrap_output.sample_sizes,...
    false_positive_rate.uncorrected,...
    'LineStyle','-',...
    'LineWidth',1,...
    'Color',colormap_correlations(1,:));
UA = plot(bootstrap_output.sample_sizes,...
    false_positive_rate.average_uncorrected,...
    'LineStyle','-',...
    'LineWidth',1.5,...
    'Color',colormap_average(1,:));
line([min(bootstrap_output.sample_sizes),...
    max(bootstrap_output.sample_sizes)],...
    [reference_fpr,...
    reference_fpr],...
    'LineStyle','--',...
    'LineWidth',1,...
    'Color',[.2 .2 .2]);
%title('Uncorrected','FontWeight','Normal')
set(gca, 'XScale', xaxis_type,...
    'XTick',sample_size_ticks,...
    'XTickLabel',strsplit(num2str(sample_size_ticks),' '),...
    'YTick',0:20:100,...
    'TickDir','out',...
    'FontName','Arial',...
    'FontSize',figure_font_size,...
    'YGrid','on');
xlim([min(bootstrap_output.sample_sizes),...
    max(bootstrap_output.sample_sizes)])
ylim([0 100])
box off
%axis square
set(gcf,'color',[1 1 1])
ylabel('False Positive Rate (%)')
xlabel('Sample size')
legend([U(1),UA(1)],...
    {'single','µ'},'location','west','Box','off')

if startsWith(lower(save_figures),'y')
    
    image_filename = strcat(output_folder,'/',...
        strrep(dataset_filename,'.csv','_fpr_uncorrected.png'));
    export_fig(image_filename,'-m10','-nocrop', '-transparent','-silent')
    
end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% FDR CORRECTED %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
figure('Position', figure_size, 'Name','FDR corrected');
axes('Position',[.25 .25 .45 .45])
%subplot(1,3,2)
hold on
F = plot(bootstrap_output.sample_sizes,...
    false_positive_rate.fdr,...
    'LineStyle','-',...
    'LineWidth',1,...
    'Color',colormap_correlations(2,:));
FA = plot(bootstrap_output.sample_sizes,...
    false_positive_rate.average_fdr,...
    'LineStyle','-',...
    'LineWidth',1.5,...
    'Color',colormap_average(2,:));
line([min(bootstrap_output.sample_sizes),...
    max(bootstrap_output.sample_sizes)],...
    [reference_fpr,...
    reference_fpr],...
    'LineStyle','--',...
    'LineWidth',1,...
    'Color',[.2 .2 .2]);
%title('FDR Corrected','FontWeight','Normal')
set(gca, 'XScale', xaxis_type,...
    'XTick',sample_size_ticks,...
    'XTickLabel',strsplit(num2str(sample_size_ticks),' '),...
    'YTick',0:20:100,...
    'TickDir','out',...
    'FontName','Arial',...
    'FontSize',figure_font_size,...
    'YGrid','on');
xlim([min(bootstrap_output.sample_sizes),...
    max(bootstrap_output.sample_sizes)])
ylim([0 100])
box off
%axis square
set(gcf,'color',[1 1 1])
ylabel('False Positive Rate (%)')
xlabel('Sample size')
legend([F(1),FA(1)],...
    {'single','µ'},'location','west','Box','off')

if startsWith(lower(save_figures),'y')
    
    image_filename = strcat(output_folder,'/',...
        strrep(dataset_filename,'.csv','_fpr_fdr_corrected.png'));
    export_fig(image_filename,'-m10','-nocrop', '-transparent','-silent')
    
end


%%%%%%%%%%%%%%%%%%%%%%%%%%% BONFERRONI CORRECTED %%%%%%%%%%%%%%%%%%%%%%%%%%
figure('Position', figure_size, 'Name','Bonferroni corrected');
axes('Position',[.25 .25 .45 .45])
%subplot(1,3,3)
hold on
B = plot(bootstrap_output.sample_sizes,...
    false_positive_rate.bonferroni,...
    'LineStyle','-',...
    'LineWidth',1,...
    'Color',colormap_correlations(3,:));
BA = plot(bootstrap_output.sample_sizes,...
    false_positive_rate.average_bonferroni,...
    'LineStyle','-',...
    'LineWidth',1.5,...
    'Color',colormap_average(3,:));
line([min(bootstrap_output.sample_sizes),...
    max(bootstrap_output.sample_sizes)],...
    [reference_fpr,...
    reference_fpr],...
    'LineStyle','--',...
    'LineWidth',1,...
    'Color',[.2 .2 .2]);
%title('Bonferroni Corrected','FontWeight','Normal')
set(gca, 'XScale', xaxis_type,...
    'XTick',sample_size_ticks,...
    'XTickLabel',strsplit(num2str(sample_size_ticks),' '),...
    'YTick',0:20:100,...
    'TickDir','out',...
    'FontName','Arial',...
    'FontSize',figure_font_size,...
    'YGrid','on');
xlim([min(bootstrap_output.sample_sizes),...
    max(bootstrap_output.sample_sizes)])
ylim([0 100])
box off
%axis square
set(gcf,'color',[1 1 1])
ylabel('False Positive Rate (%)')
xlabel('Sample size')
legend([B(1),BA(1)],...
    {'single','µ'},'location','west','Box','off')

% sgtitle(figure_title,'FontWeight','normal',...
%     'FontName','Arial',...
%     'FontSize',figure_font_size)

if startsWith(lower(save_figures),'y')
    
    image_filename = strcat(output_folder,'/',...
        strrep(dataset_filename,'.csv','_fpr_bonferroni_corrected.png'));
    export_fig(image_filename,'-m10','-nocrop', '-transparent','-silent')
    
end

end


